### ISSUE TITLE
python library error

### ISSUE THREAD

**Issue by SONG-WONHO** [kakao/khaiii#97]
안녕하세요. 소개된 빌드 과정으로 설치한뒤 테스트 프로그램까지 패스했습니다. 다만, 파이썬 라이브러리로 임포트 후 사용시 아래와 같은 에러가 발생합니다.

>>> from khaiii import KhaiiiApi
>>> api = KhaiiiApi()
ERROR:root:current working directory: /khaiii/build/package_python
ERROR:root:library directory: /khaiii/build/package_python/khaiii/lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/khaiii/build/package_python/khaiii/khaiii.py", line 171, in __init__
    raise KhaiiiExcept('fail to find library: {}'.format(lib_name))
khaiii.khaiii.KhaiiiExcept: fail to find library: libkhaiii.so

혹시 저와 같은 문제가 있으신 분 계시거나 해결방법이 있을까요?

**Comment by SONG-WONHO** [comment]
Python interpreter에서 문제가 발생했는데, script로 하니까 정상 실행 되네요!
